### ISSUE TITLE
Cannot Auto Logic the new Agreement Page

### ISSUE THREAD

**Issue by bajinsheng** [NaiboWang/NUS_literature_quick_access#2]
Thanks for this excellent script!

However, when I click a paper link, it shows me an agreement page, but the script cannot autofill it. I have to manually click it and continue to see the pdf.

I am wondering is there any configuration for this?

![image](https://github.com/NaiboWang/NUS_literature_quick_access/assets/30287768/a849711c-6e07-4a65-94f9-cb0c24b716b9)

**Comment by NaiboWang** [comment]
Hi, you can try update to version 5.2 and see if you can automatically login.

And note that the login operation will only require once when you open a browser.

**Comment by bajinsheng** [comment]
I see, so it still requires manual login once.
Thanks!

**Comment by NaiboWang** [comment]
Hi Jinsheng,

The bug is fixed now, and you can update to version 5.3 to make it automatically login. Please reply whether it works for you.

Also, if you want the script help to automatically input your username and password, please modify the following lines through TamperMonkey:

![image](https://github.com/NaiboWang/NUS_literature_quick_access/assets/30287768/5184214d-e2fa-4f05-a484-5423002c1d64)

And I will be very thankful if you recommend this script to your friends who need it~

Enjoy and have a good day!
